version: "3.8"

services:
  backend:
    build: .
    container_name: vacancy
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/vacancydb
    networks:
      - vacancy-net

  mongo:
    image: mongo:6
    container_name: vacancy-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - vacancy-net

volumes:
  mongodb_data:

networks:
  vacancy-net:
